#!/bin/bash
set -eo pipefail
# Debug of environment variables
echo "MEGALINTER_ENTRYPOINT: ${MEGALINTER_ENTRYPOINT}"
echo "GITHUB_REF: ${GITHUB_REF}"
echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
echo "GITHUB_SHA: ${GITHUB_SHA}"
echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
echo "DEFAULT_WORKSPACE: ${DEFAULT_WORKSPACE}"
echo "CI_ACTION_RUN_URL: ${CI_ACTION_RUN_URL}"
echo "APPLY_FIXES: ${APPLY_FIXES}"
